name: Check Email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  check_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install imaplib2 beautifulsoup4

      - name: Check Email and Extract Code
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python extract_code.py

      - name: Update index.html with codes
        run: |
          python update_index.py
