name: 读取email验证码

on:
  workflow_dispatch:
    inputs:
      emall_username:
        description: 'EMAIL_USERNAME'
        required: true
        type: string
      emall_password:
        description: 'EMAIL_PASSWORD'
        required: true
        type: string
      emall_imap:
        description: 'EMAIL_IMAP'
        required: true
        type: string
      code_phonenumber:
        description: 'CODE_PHONENUMBER'
        required: true
        type: string
      code_blockwords:
        description: 'CODE_BLOCKWORDS'
        required: true
        type: string
      code_blackwords:
        description: 'CODE_BLACKWORDS'
        required: true
        type: string

jobs:
  check_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install imaplib2 beautifulsoup4

      - name: Check Email and Extract Code
        env:
          EMAIL_USERNAME: ${{ github.event.inputs.emall_username }}
          EMAIL_PASSWORD: ${{ github.event.inputs.emall_password }}
          EMAIL_IMAP: ${{ github.event.inputs.emall_imap }}
          CODE_BLOCKWORDS: ${{ github.event.inputs.code_blockwords }}
        run: |
          python extract_code.py

      - name: Update index.html with codes
        env:
          CODE_PHONENUMBER: ${{ github.event.inputs.code_phonenumber }}
          CODE_BLACKWORDS: ${{ github.event.inputs.code_blackwords }}
        run: |
          python update_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add index.html codes.txt
          git commit -m "Update index.html with new verification codes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Print extracted codes
        run: |
          cat codes.txt  # 打印验证码
