name: Check Email

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  check_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install imaplib2 beautifulsoup4

      - name: Check Email and Extract Code
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python extract_code.py

      - name: Update index.html with codes
        run: |
          python update_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update index.html with new verification codes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print extracted codes
        run: |
          cat codes.txt  # 打印验证码
